routes/web.php
<?php

/* ROUTES SITE */
Route::get('/','PagesController@home')->name('home');// Recupera as informações da função em PagesController.php
Route::get('/conheca','PagesController@conheca')->name('conheca');// Recupera as informações da função em PagesController.php
Route::get('servicos','PagesController@servicos')->name('servicos');// Recupera as informações da função em PagesController.php
Route::get('/contato','PagesController@contato')->name('contato');// Recupera as informações da função em PagesController.php
Route::get('/servico/{slug}','PagesController@servico')->name('servico');
Route::get('politicasdeprivacidade','PagesController@privacidade')->name('politicasdeprivacidade');// Recupera as informações da função em PagesController.php
Route::get('compra','PagesController@compra')->name('compra');// Recupera as informações da função em PagesController.php
Route::get('cancelamento','PagesController@cancelamento')->name('cancelamento');// Recupera as informações da função em PagesController.php

Route::get('/cadastro','FormsController@index')->name('cadastro');// Recupera as informações da função em PagesController.php
Route::post('/cadastro/inserir', 'FormsController@cadastro')->name('userloja.cadastro');
Route::post('/contato/enviar', 'PagesController@contatoenviar')->name('contato.enviar');

Route::get('/pagamento/status', 'RetornopagamentoController@pagamentostatus')->name('pagamento.status');






/* ROUTES AUTHENTICATE */
Route::group(['prefix'=>'cms'], function(){
	Auth::routes();
});

/* ROUTES CMS */
Route::group(['prefix'=>'cms','middleware' => 'auth'], function(){
	Route::get('/', 'DashboardController@index')->name('dashboard');
	Route::get('dashboard', 'DashboardController@index')->name('dashboard');

	Route::post('/busca', 'PedidosController@index')->name('pedidos.busca');
	Route::get('/busca', 'PedidosController@index')->name('pedidos.busca');

	//Static Pages
	Route::resource('pages', 'PagesController');
	Route::resource('informacoes', 'InformacoesController');

	//Dynamic Content
	Route::resource('posts', 'PostsController');
	Route::resource('categorias', 'CategoriasController');
	Route::resource('galerias', 'GaleriasController');
	Route::resource('usuarios', 'UsersController');
	Route::resource('usuariosloja', 'UserslojaController');
	Route::resource('profissionais', 'ProfissionaisController');
	Route::resource('pedidos', 'PedidosController');
	Route::resource('slides', 'SlidesController');
	Route::resource('excecoes', 'ExcecoesController');
	
	//Medias content
	Route::get('galerias/files/{id}', 'GaleriasController@filesall')->name('files.all');
	Route::post('galerias/files/up/{id}', 'GaleriasController@fileup')->name('file.up');
	Route::post('galerias/files/del/{id}', 'GaleriasController@filedel')->name('file.del');
});

app/Http/Controllers/ExcecoesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\PostsRequest;
use Illuminate\Support\Facades\Session;

use App\Post;
use App\Excecao;

class ExcecoesController extends Controller
{
    
	/**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
	public function index(Request $request)
    {

        /* 1 = Administrador | 2 = Cliente | 3 = Conteudoria | 4 = Editor | 5 = Redator */
        if(!$request->user()->authorizeRoles(['1'])) {
            $title = "Acesso não autorizado";
            return view('cms.errors.401', compact('title'));
        }

        $excecoes = Excecao::orderBy('id', 'DESC')->paginate(10);
        $title = 'Listagem de Exceções';

        return view('cms.excecoes.index', compact('title', 'excecoes'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        /* 1 = Administrador | 2 = Cliente | 3 = Conteudoria | 4 = Editor | 5 = Redator */
        if(!$request->user()->authorizeRoles(['1'])) {
            $title = "Acesso não autorizado";
            return view('cms.errors.401', compact('title'));
        }

        $servicos = Post::
        select('id','title')
        ->get();

        $title = 'Inserindo nova exceção para um serviço';

        return view('cms.excecoes.create', compact('title','servicos'));
    }



    public function store(Request $request)
    {
        $new = $request->all();

        $data = str_replace("/", "-", $new['data']);
    	$new['data']=date('Y-m-d', strtotime($data));

        Excecao::create($new);

        Session::flash('message', 'Adicionado com sucesso!');
        Session::flash('class', 'success');
        return redirect()->route('excecoes.index');
    }

    public function destroy(Request $request, $id)
    {
        /* 1 = Administrador | 2 = Cliente | 3 = Conteudoria | 4 = Editor | 5 = Redator */
        if(!$request->user()->authorizeRoles(['1'])) {
            $title = "Acesso não autorizado";
            return view('cms.errors.401', compact('title'));
        }

        $excecao = Excecao::findOrFail($id);

        $excecao->delete();

        Session::flash('message', 'Removido com sucesso!');
        Session::flash('class', 'danger');
        return redirect()->route('excecoes.index');
    }


}

resources/views/cms/excecoes/create.blade.php
@extends('layouts.cms_app')

@section('content')
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <h4 class="page-title">{{$title}}</h4>
                        <!-- breadcrumb -->
		                <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Painel</a></li>
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Exceções</a></li>
                            <li class="breadcrumb-item active">{{$title}}</li>
		                </ol>
		                <!-- breadcrumb -->
                    </div>
                </div>
            </div> <!-- end row -->
            
            <!-- Verifica e mostra erros dos campos obrigatórios -->
            @include('cms.includes.error_messages')

            <div class="row">
                <!-- Verifica e mostra mensagem de sucesso -->
                @include('cms.includes.alert_messages')
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="card m-b-20">
	                    <div class="card-body">
	                    	<form action="{{route('excecoes.store')}}" method="POST" enctype="multipart/form-data">
	                    		{{ csrf_field() }}

                                <div class="form-group row">
                                    <div class="col-md-12">  <!-- <post_id> do post -->
                                        <label for="post_id">Serviço</label>
                                        <select name="post_id" class="form-control" required>
                                            <option value="">Selecione a serviço</option>
                                            @foreach($servicos as $servico)
                                            <option value="{{$servico->id}}">{{$servico->title}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
	                    		
	                    		<div class="form-group row">
		                            <div class="col-md-12"> <!-- <label> do conteúdo -->
										<label for="label">Data da exceção</label>
	                                	<input class="form-control dataexcecao" type="text" placeholder="Exemplo: 01/01/2019" name="data" required/>
		                            </div>
		                        </div>

                                <div class="form-group row">
                                    <div class="col-md-12"> <!-- <label> do conteúdo -->
                                        <label for="label">Observação</label>
                                        <input class="form-control" type="text" name="content" />
                                    </div>
                                </div>

		                        <div class="form-group row">
                                    <div class="col-md-12 text-right">
                                        <button class="btn btn-primary btn-lg"><i class="fas fa-save"></i> Salvar alterações</button>
                                        <a href="{{route('excecoes.index')}}" class="btn btn-danger btn-lg"><i class="fas fa-window-close"></i> Cancelar</a>
                                    </div>
		                        </div>
	                        </form>
	                    </div>
                    </div>
                </div> <!-- end col-6 -->
                <div class="col-3"></div>
            </div> <!-- end row -->        
        </div> <!-- container-fluid -->
    </div> <!-- content -->
</div>
@endsection

@section('scripts')
    @include('cms.includes.tinymce')
    <script type="text/javascript" charset="utf-8">
        
        //Função que exibe a imagem antes de subir o arquivo
         $(function () {
            $(".perfilimg").change(function () {
                readURL(this);
            });
        });
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    //alert(e.target.result);
                    $('.img-avatar').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
        //Função que exibe a imagem antes de subir o arquivo

    </script>
@endsection

resources/views/cms/excecoes/edit.blade.php
@extends('layouts.cms_app')

@section('content')
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <h4 class="page-title">{{$title}}</h4>
                        <!-- breadcrumb -->
		                <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Painel</a></li>
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Páginas</a></li>
                            <li class="breadcrumb-item active">{{$title}}</li>
		                </ol>
		                <!-- breadcrumb -->
                    </div>
                </div>
            </div> <!-- end row -->
            
            <!-- Verifica e mostra erros dos campos obrigatórios -->
            @include('cms.includes.error_messages')

            <div class="row">
                <!-- Verifica e mostra mensagem de sucesso -->
                @include('cms.includes.alert_messages')
                <div class="col-12">
                    <div class="card m-b-20">
	                    <div class="card-body">
	                    	<form action="{{route('profissionais.update', $profissional->id)}}" method="POST" enctype="multipart/form-data">
	                    		{{ csrf_field() }}
                                <input type="hidden" name="_method" value="PUT" />

		                        <div class="form-group row">
                                    <div class="col-md-12"> <!-- <label> do conteúdo -->
                                        <label for="label">Nome</label>
                                        <input class="form-control" type="text" name="nome" value="{{$profissional->nome}}" />
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-md-4"> <!-- <perfilimg> principal da página -->
                                        <img src="{{$profissional->perfilimg ? $profissional->perfilimg : 'https://via.placeholder.com/100x100'}}" alt="" class="mb-3 img-avatar" width="100" /><br>
                                        <label for="perfilimg">Imagem do <small class="badge badge-primary">Perfil</small></label>
                                        <input type="file" name="perfilimg" class="form-control perfilimg" />
                                    </div>
                                </div>

		                        <hr>

		                        <div class="form-group row">
                                    <div class="col-md-12 text-right">
                                        <button class="btn btn-primary btn-lg"><i class="fas fa-save"></i> Salvar alterações</button>
                                        <a href="{{route('categorias.index')}}" class="btn btn-danger btn-lg"><i class="fas fa-window-close"></i> Cancelar</a>
                                    </div>
		                        </div>
	                        </form>
	                    </div>
                    </div>
                </div> <!-- end col -->
            </div> <!-- end row -->        
        </div> <!-- container-fluid -->
    </div> <!-- content -->
</div>
@endsection


@section('scripts')
    <script type="text/javascript" charset="utf-8">
        
        //Função que exibe a imagem antes de subir o arquivo
         $(function () {
            $(".perfilimg").change(function () {
                readURL(this);
            });
        });
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    //alert(e.target.result);
                    $('.img-avatar').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
        //Função que exibe a imagem antes de subir o arquivo

    </script>
@endsection

resources/views/cms/excecoes/index.blade.php
@extends('layouts.cms_app')

@section('content')
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <h4 class="page-title">{{$title}}</h4>
                        <!-- breadcrumb -->
		                <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Painel</a></li>
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Profissionais</a></li>
                            <li class="breadcrumb-item active">{{$title}}</li>
		                </ol>
		                <!-- breadcrumb -->
                    </div>
                </div>
            </div> <!-- end row -->

            <div class="row">
                <!-- Verifica e mostra mensagem de sucesso -->
                @include('cms.includes.alert_messages')
                <div class="col-12">
                    <div class="card m-b-20">
                        <div class="card-body">
                        	<table class="table table-striped mb-0">
	                        	<thead>
									<tr>
                                        <th>DATA</th>
                                        <th>OBSERVAÇÃO</th>
                                        <th>SERVIÇO</th>
			                            <th>ATUALIZAÇÃO</th>
			                            <th>AÇÕES</th>
		                            </tr>
	                        	</thead>
							
								<tbody>
                                @if(count($excecoes)>0)
    								@foreach($excecoes as $excecao)
    	                        	<tr>
    		                            <th scope="row">{{$excecao->data}}</th>
                                        <td>{{$excecao->content}}</td>
                                        <td>{{$excecao->servico->title}}</td>
    		                            <td><div class="badge badge-pill badge-info">{{$excecao->updated_at ? $excecao->updated_at->diffForHumans() : 'Não foi atualizado!'}}</div></td>
    		                            <td>
                                            <form action="{{route('excecoes.destroy', $excecao->id)}}" method="POST">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE" />

    										<div class="btn-group" role="group" aria-label="Basic example"
    										>
    											<a href="{{route('excecoes.edit', $excecao->id)}}" class="btn btn-primary"><i class="fas fa-edit"></i> Editar</a>
    											<button class="btn btn-danger"><i class="fas fa-trash"></i> Deletar</button>
    										</div>
                                            </form>
    		                            </div>
    		                        </tr>
    		                        @endforeach
                                @else
                                    <tr>
                                        <td>
                                           Não há exceções cadastradas!
                                        </td>
                                    </tr>
                                @endif
		                        </tbody>
	                        </table>
                        </div>
                    </div>
                </div> <!-- end col -->
            </div> <!-- end row -->

            <div class="row">
                <div class="col-md-12">
                    {{$excecoes->links()}}
                </div>
            </div>
        </div> <!-- container-fluid -->
    </div> <!-- content -->
</div>
@endsection