routes/web.php
<?php

/* ROUTES SITE */
Route::get('/','PagesController@home')->name('home');// Recupera as informações da função em PagesController.php
Route::get('/conheca','PagesController@conheca')->name('conheca');// Recupera as informações da função em PagesController.php
Route::get('servicos','PagesController@servicos')->name('servicos');// Recupera as informações da função em PagesController.php
Route::get('/contato','PagesController@contato')->name('contato');// Recupera as informações da função em PagesController.php
Route::get('/servico/{slug}','PagesController@servico')->name('servico');
Route::get('politicasdeprivacidade','PagesController@privacidade')->name('politicasdeprivacidade');// Recupera as informações da função em PagesController.php
Route::get('compra','PagesController@compra')->name('compra');// Recupera as informações da função em PagesController.php
Route::get('cancelamento','PagesController@cancelamento')->name('cancelamento');// Recupera as informações da função em PagesController.php

Route::get('/cadastro','FormsController@index')->name('cadastro');// Recupera as informações da função em PagesController.php
Route::post('/cadastro/inserir', 'FormsController@cadastro')->name('userloja.cadastro');
Route::post('/contato/enviar', 'PagesController@contatoenviar')->name('contato.enviar');

Route::get('/pagamento/status', 'RetornopagamentoController@pagamentostatus')->name('pagamento.status');






/* ROUTES AUTHENTICATE */
Route::group(['prefix'=>'cms'], function(){
	Auth::routes();
});

/* ROUTES CMS */
Route::group(['prefix'=>'cms','middleware' => 'auth'], function(){
	Route::get('/', 'DashboardController@index')->name('dashboard');
	Route::get('dashboard', 'DashboardController@index')->name('dashboard');

	Route::post('/busca', 'PedidosController@index')->name('pedidos.busca');
	Route::get('/busca', 'PedidosController@index')->name('pedidos.busca');

	//Static Pages
	Route::resource('pages', 'PagesController');
	Route::resource('informacoes', 'InformacoesController');

	//Dynamic Content
	Route::resource('posts', 'PostsController');
	Route::resource('categorias', 'CategoriasController');
	Route::resource('galerias', 'GaleriasController');
	Route::resource('usuarios', 'UsersController');
	Route::resource('usuariosloja', 'UserslojaController');
	Route::resource('profissionais', 'ProfissionaisController');
	Route::resource('pedidos', 'PedidosController');
	Route::resource('slides', 'SlidesController');
	Route::resource('excecoes', 'ExcecoesController');
	
	//Medias content
	Route::get('galerias/files/{id}', 'GaleriasController@filesall')->name('files.all');
	Route::post('galerias/files/up/{id}', 'GaleriasController@fileup')->name('file.up');
	Route::post('galerias/files/del/{id}', 'GaleriasController@filedel')->name('file.del');
});

app/Http/Controllers/ProfissionaisController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\PostsRequest;
use Illuminate\Support\Facades\Session;

use App\Profissional;
use App\File;

class ProfissionaisController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        /* 1 = Administrador | 2 = Cliente | 3 = Conteudoria | 4 = Editor | 5 = Redator */
        if(!$request->user()->authorizeRoles(['1','2','3','4'])) {
            $title = "Acesso não autorizado";
            return view('cms.errors.401', compact('title'));
        }

        $profissionais = Profissional::all();
        $title = 'Listagem de Profissionais';

        return view('cms.profissionais.index', compact('title', 'profissionais'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        /* 1 = Administrador | 2 = Cliente | 3 = Conteudoria | 4 = Editor | 5 = Redator */
        if(!$request->user()->authorizeRoles(['1','2','3','4'])) {
            $title = "Acesso não autorizado";
            return view('cms.errors.401', compact('title'));
        }

        $title = 'Inserindo novo Profissional';

        return view('cms.profissionais.create', compact('title'));
    }


     /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        /* 1 = Administrador | 2 = Cliente | 3 = Conteudoria | 4 = Editor | 5 = Redator */
        if(!$request->user()->authorizeRoles(['1','2','3','4'])) {
            $title = "Acesso não autorizado";
            return view('cms.errors.401', compact('title'));
        }

        $profissional = Profissional::findOrFail($id);
        $title = 'Editando: '.$profissional->name;

        if($request->hasFile('perfilimg')){
            $file = $request->file('perfilimg');
            $file_name = time().'-'.$file->getClientOriginalName();
            $file_path = 'uploads/profissionais/';

            $file->move($file_path, $file_name);

            $up['perfilimg'] = $file_name;

        }

        return view('cms.profissionais.edit', compact('title', 'profissional'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $new = $request->all();

        if($request->hasFile('perfilimg')){
            $file = $request->file('perfilimg');
            $file_name = time().'-'.$file->getClientOriginalName();
            $file_path = 'uploads/profissionais/';

            $file->move($file_path, $file_name);

            if($new['perfilimg'] != "") {
                $new['perfilimg'] = $file_name;
            }
        }

        Profissional::create($new);

        Session::flash('message', 'Adicionado com sucesso!');
        Session::flash('class', 'success');
        return redirect()->route('profissionais.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $profissional = Profissional::findOrFail($id);
        $up = $request->all();

        if($request->hasFile('perfilimg')){
            $file = $request->file('perfilimg');
            $file_name = time().'-'.$file->getClientOriginalName();
            $file_path = 'uploads/profissionais/';

            $file->move($file_path, $file_name);

            if($up['perfilimg'] != "") {
                $up['perfilimg'] = $file_name;
            }
        }

        $profissional->update($up);

        Session::flash('message', 'Editado com sucesso!');
        Session::flash('class', 'success');
        return redirect()->route('profissionais.edit', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        /* 1 = Administrador | 2 = Cliente | 3 = Conteudoria | 4 = Editor | 5 = Redator */
        if(!$request->user()->authorizeRoles(['1','2','3','5'])) {
            $title = "Acesso não autorizado";
            return view('cms.errors.401', compact('title'));
        }
        
        $profissional = Profissional::findOrFail($id);

        $profissional->delete();

        Session::flash('message', 'Removido com sucesso!');
        Session::flash('class', 'danger');
        return redirect()->route('profissionais.index');
    }
}

resources/views/cms/profissionais/create.blade.php
@extends('layouts.cms_app')

@section('content')
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <h4 class="page-title">{{$title}}</h4>
                        <!-- breadcrumb -->
		                <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Painel</a></li>
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Profissionais</a></li>
                            <li class="breadcrumb-item active">{{$title}}</li>
		                </ol>
		                <!-- breadcrumb -->
                    </div>
                </div>
            </div> <!-- end row -->
            
            <!-- Verifica e mostra erros dos campos obrigatórios -->
            @include('cms.includes.error_messages')

            <div class="row">
                <!-- Verifica e mostra mensagem de sucesso -->
                @include('cms.includes.alert_messages')
                <div class="col-12">
                    <div class="card m-b-20">
	                    <div class="card-body">
	                    	<form action="{{route('profissionais.store')}}" method="POST" enctype="multipart/form-data">
	                    		{{ csrf_field() }}
	                    		
	                    		<div class="form-group row">
		                            <div class="col-md-12"> <!-- <label> do conteúdo -->
										<label for="label">Nome</label>
	                                	<input class="form-control" type="text" name="nome" />
		                            </div>
		                        </div>

                                <div class="form-group row">
                                    <div class="col-md-4"> <!-- <perfilimg> principal da página -->
                                        <img src="https://via.placeholder.com/100x100" alt="" class="mb-3 img-avatar" width="100" /><br>
                                        <label for="perfilimg">Imagem do <small class="badge badge-primary">Perfil</small></label>
                                        <input type="file" name="perfilimg" class="form-control perfilimg" />
                                    </div>
                                </div>

		                        <hr>

		                        <div class="form-group row">
                                    <div class="col-md-12 text-right">
                                        <button class="btn btn-primary btn-lg"><i class="fas fa-save"></i> Salvar alterações</button>
                                        <a href="{{route('profissionais.index')}}" class="btn btn-danger btn-lg"><i class="fas fa-window-close"></i> Cancelar</a>
                                    </div>
		                        </div>
	                        </form>
	                    </div>
                    </div>
                </div> <!-- end col -->
            </div> <!-- end row -->        
        </div> <!-- container-fluid -->
    </div> <!-- content -->
</div>
@endsection

@section('scripts')
    @include('cms.includes.tinymce')
    <script type="text/javascript" charset="utf-8">
        
        //Função que exibe a imagem antes de subir o arquivo
         $(function () {
            $(".perfilimg").change(function () {
                readURL(this);
            });
        });
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    //alert(e.target.result);
                    $('.img-avatar').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
        //Função que exibe a imagem antes de subir o arquivo

    </script>
@endsection

resources/views/cms/profissionais/edit.blade.php
@extends('layouts.cms_app')

@section('content')
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <h4 class="page-title">{{$title}}</h4>
                        <!-- breadcrumb -->
		                <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Painel</a></li>
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Páginas</a></li>
                            <li class="breadcrumb-item active">{{$title}}</li>
		                </ol>
		                <!-- breadcrumb -->
                    </div>
                </div>
            </div> <!-- end row -->
            
            <!-- Verifica e mostra erros dos campos obrigatórios -->
            @include('cms.includes.error_messages')

            <div class="row">
                <!-- Verifica e mostra mensagem de sucesso -->
                @include('cms.includes.alert_messages')
                <div class="col-12">
                    <div class="card m-b-20">
	                    <div class="card-body">
	                    	<form action="{{route('profissionais.update', $profissional->id)}}" method="POST" enctype="multipart/form-data">
	                    		{{ csrf_field() }}
                                <input type="hidden" name="_method" value="PUT" />

		                        <div class="form-group row">
                                    <div class="col-md-12"> <!-- <label> do conteúdo -->
                                        <label for="label">Nome</label>
                                        <input class="form-control" type="text" name="nome" value="{{$profissional->nome}}" />
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-md-4"> <!-- <perfilimg> principal da página -->
                                        <img src="{{$profissional->perfilimg ? $profissional->perfilimg : 'https://via.placeholder.com/100x100'}}" alt="" class="mb-3 img-avatar" width="100" /><br>
                                        <label for="perfilimg">Imagem do <small class="badge badge-primary">Perfil</small></label>
                                        <input type="file" name="perfilimg" class="form-control perfilimg" />
                                    </div>
                                </div>

		                        <hr>

		                        <div class="form-group row">
                                    <div class="col-md-12 text-right">
                                        <button class="btn btn-primary btn-lg"><i class="fas fa-save"></i> Salvar alterações</button>
                                        <a href="{{route('categorias.index')}}" class="btn btn-danger btn-lg"><i class="fas fa-window-close"></i> Cancelar</a>
                                    </div>
		                        </div>
	                        </form>
	                    </div>
                    </div>
                </div> <!-- end col -->
            </div> <!-- end row -->        
        </div> <!-- container-fluid -->
    </div> <!-- content -->
</div>
@endsection


@section('scripts')
    <script type="text/javascript" charset="utf-8">
        
        //Função que exibe a imagem antes de subir o arquivo
         $(function () {
            $(".perfilimg").change(function () {
                readURL(this);
            });
        });
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    //alert(e.target.result);
                    $('.img-avatar').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
        //Função que exibe a imagem antes de subir o arquivo

    </script>
@endsection

resources/views/cms/profissionais/index.blade.php
@extends('layouts.cms_app')

@section('content')
<div class="content-page">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <h4 class="page-title">{{$title}}</h4>
                        <!-- breadcrumb -->
		                <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Painel</a></li>
                            <li class="breadcrumb-item"><a href="javascript:void(0);">Profissionais</a></li>
                            <li class="breadcrumb-item active">{{$title}}</li>
		                </ol>
		                <!-- breadcrumb -->
                    </div>
                </div>
            </div> <!-- end row -->

            <div class="row">
                <!-- Verifica e mostra mensagem de sucesso -->
                @include('cms.includes.alert_messages')
                <div class="col-12">
                    <div class="card m-b-20">
                        <div class="card-body">
                        	<table class="table table-striped mb-0">
	                        	<thead>
									<tr>
			                            <th>ID</th>
                                        <th>NOME</th>
                                        <th>PERFIL</th>
			                            <th>ATUALIZAÇÃO</th>
			                            <th>AÇÕES</th>
		                            </tr>
	                        	</thead>
							
								<tbody>
                                @if(count($profissionais)>0)
    								@foreach($profissionais as $profissional)
    	                        	<tr>
    		                            <th scope="row">{{$profissional->id}}</th>
                                        <td>{{$profissional->nome}}</td>
                                        <td><div class="div-circle"><img src="{{$profissional->perfilimg ? $profissional->perfilimg : 'https://via.placeholder.com/50x50'}}" alt="" class="mb-3 img-circle" width="50" /></div></td>
    		                            <td><div class="badge badge-pill badge-info">{{$profissional->updated_at ? $profissional->updated_at->diffForHumans() : 'Não foi atualizado!'}}</div></td>
    		                            <td>
                                            <form action="{{route('profissionais.destroy', $profissional->id)}}" method="POST">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="_method" value="DELETE" />

    										<div class="btn-group" role="group" aria-label="Basic example"
    										>
    											<a href="{{route('profissionais.edit', $profissional->id)}}" class="btn btn-primary"><i class="fas fa-edit"></i> Editar</a>
    											<button class="btn btn-danger"><i class="fas fa-trash"></i> Deletar</button>
    										</div>
                                            </form>
    		                            </div>
    		                        </tr>
    		                        @endforeach
                                @else
                                    <tr>
                                        <td>
                                           Não há profissionais cadastrados! 
                                        </td>
                                    </tr>
                                @endif
		                        </tbody>
	                        </table>
                        </div>
                    </div>
                </div> <!-- end col -->
            </div> <!-- end row -->

            
        </div> <!-- container-fluid -->
    </div> <!-- content -->
</div>
@endsection